
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend/deploy.yml
- frontend/service.yml
- backend/deploy.yml
- backend/service.yml
- ingress.yml
- argocd/application.yml
  
images:
- name: 654654554686.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/backend
  newName: 654654554686.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/backend
  newTag: v1.0

- name: 654654554686.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/frontend
  newName: 654654554686.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/frontend
  newTag: v1.0
